name: clothes_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  global_configuration: ^2.0.0-nullsafety.1
  firebase_core: ^2.1.1
  firebase_auth: ^4.2.0
  get_storage: ^2.0.3
  flutter_signin_button: 2.0.0
  introduction_screen: 3.1.4
  google_fonts: ^4.0.4
  permission_handler: 10.2.0
  intl: ^0.18.1
  flutter_html: ^3.0.0-alpha.6
  image_picker: ^0.8.7
  image_cropper: ^3.0.2
  flutter_exif_rotation: ^0.5.1
  date_field: ^3.0.5
  http: ^0.13.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/images/icon/
    - assets/images/product/
    - assets/images/product/man/man-jacket/
    - assets/images/product/man/man-kaki-pant/
    - assets/images/product/man/man-polo/
    - assets/images/product/man/man-shirt/
    - assets/images/product/man/man-t-shirt/
    - assets/images/product/man/man-trouser/
    - assets/images/product/woman/woman-dress/
    - assets/images/product/woman/woman-jacket/
    - assets/images/product/woman/woman-kaki-pant/
    - assets/images/product/woman/woman-skirt/
    - assets/images/product/woman/woman-t-shirt/
  uses-material-design: true
