name: clothes_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  global_configuration: ^2.0.0-nullsafety.1
  firebase_core: ^2.1.1
  firebase_auth: ^4.2.0
  get_storage: ^2.0.3
  flutter_signin_button: 2.0.0
  introduction_screen: 3.1.4
  google_fonts: 3.0.1
  permission_handler: 10.2.0
  intl: 0.18.0
  flutter_html: ^3.0.0-alpha.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/images/icon/
  uses-material-design: true
